platform :ios, '9.0'

pod 'BlocksKit', '~> 2.2.5'
pod 'AFNetworking', '~> 2.6.0'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'BlocksKit', '~> 2.2.5'
pod 'IQKeyboardManager', '~> 3.3.1'
pod 'Masonry', '~> 0.6.2'
pod 'QBImagePickerController', '<= 2.5.2'
pod 'MJRefresh', '~> 2.4.9'
